/* -----------------------------------------------------------\
|  This code was generated by Oilexer.                        |
|  Version: 1.0.0.0                                           |
|-------------------------------------------------------------|
|  To ensure the code works properly,                         |
|  please do not make any changes to the file.                |
|-------------------------------------------------------------|
|  The specific language is C# (Runtime version: v2.0.50727)  |
|  Sub-tool Name: Oilexer.CSharpCodeTranslator                |
|  Sub-tool Version: 1.0.0.0                                  |
\----------------------------------------------------------- */
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;
 /*---------------------------------------------------------------------\
 | Copyright © 2008-2011 Allen C. [Alexander Morou] Copeland Jr.        |
 |----------------------------------------------------------------------|
 | The Abstraction Project's code is provided under a contract-release  |
 | basis.  DO NOT DISTRIBUTE and do not use beyond the contract terms.  |
 \-------------------------------------------------------------------- */

namespace AllenCopeland.Abstraction.Slf.Languages.Oilexer.Tokens
{
    // Module: RootModule
    [DebuggerDisplay("{StringForm}")]
    public partial class RegularLanguageScanData :
        List<RegularLanguageScanData.Entry>
    {
        //#region RegularLanguageScanData data members
        private long location;
        //#endregion // RegularLanguageScanData data members
        //#region RegularLanguageScanData properties
        public long Location
        {
            get
            {
                return this.location;
            }
        }
        //#endregion // RegularLanguageScanData properties
        //#region RegularLanguageScanData .ctors
        public RegularLanguageScanData(long location)
        {
            this.location = location;
        }
        //#endregion // RegularLanguageScanData .ctors

        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            bool first = true;
            foreach (var entry in this)
            {
                if (first)
                    first = false;
                else
                    sb.Append(" & ");
                sb.Append(entry.ToString());
            }
            return sb.ToString();
        }

        private string StringForm
        {
            get
            {
                return this.ToString();
            }
        }
    }
}
 /* --------------------------------------------------------------------------------------\
 |  This file took 00:00:00.0008193 to generate.                                          |
 |  Date generated: 8/26/2011 4:13:06 PM                                                  |
 |  There were 3 types used by this file                                                  |
 |  System.Int64, List`1[[RegularLanguageScanData+Entry]], RegularLanguageScanData+Entry  |
 |----------------------------------------------------------------------------------------|
 |  There were 1 assemblies referenced:                                                   |
 |  mscorlib                                                                              |
 \-------------------------------------------------------------------------------------- */
