//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllenCopeland.Abstraction.Slf.Languages.Oilexer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ParserResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParserResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AllenCopeland.Abstraction.Slf.Properties.ParserResources", typeof(ParserResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OILParserAssembly.
        /// </summary>
        internal static string DefaultAssemblyName {
            get {
                return ResourceManager.GetString("DefaultAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnnamedGrammar.
        /// </summary>
        internal static string DefaultGrammarName {
            get {
                return ResourceManager.GetString("DefaultGrammarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OiLexer.
        /// </summary>
        internal static string DefaultLexerName {
            get {
                return ResourceManager.GetString("DefaultLexerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OilexerParser.
        /// </summary>
        internal static string DefaultParserName {
            get {
                return ResourceManager.GetString("DefaultParserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compiler detected a sequence of tokens which yielded an ambiguity: Multiple states entered a terminal point with no more look-ahead available.  See error details written to file..
        /// </summary>
        internal static string GrammarCompilerErrors_AmbiguousPathDetected {
            get {
                return ResourceManager.GetString("GrammarCompilerErrors_AmbiguousPathDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate entry detected: &apos;{0}&apos; is defined multiple times..
        /// </summary>
        internal static string GrammarCompilerErrors_DuplicateEntryError {
            get {
                return ResourceManager.GetString("GrammarCompilerErrors_DuplicateEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Duplicate, see above multiple definition error above..
        /// </summary>
        internal static string GrammarCompilerErrors_DuplicateEntryReference {
            get {
                return ResourceManager.GetString("GrammarCompilerErrors_DuplicateEntryReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid preprocessor &apos;defined&apos; target ({0})..
        /// </summary>
        internal static string GrammarCompilerErrors_InvalidIsDefinedTarget {
            get {
                return ResourceManager.GetString("GrammarCompilerErrors_InvalidIsDefinedTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid preprocessor condition ({0}), evaluation failed..
        /// </summary>
        internal static string GrammarCompilerErrors_InvalidPreprocessorCondition {
            get {
                return ResourceManager.GetString("GrammarCompilerErrors_InvalidPreprocessorCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule `{0}` is marked as a collapse point; however it does not match the idea of each expression being a single target of either a token or a rule..
        /// </summary>
        internal static string GrammarCompilerErrors_InvalidRuleCollapsePoint {
            get {
                return ResourceManager.GetString("GrammarCompilerErrors_InvalidRuleCollapsePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language defined error ({0}):
        ///{1}.
        /// </summary>
        internal static string GrammarCompilerErrors_LanguageDefinedError {
            get {
                return ResourceManager.GetString("GrammarCompilerErrors_LanguageDefinedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A literal ({0}) was encountered of an unexpected or unknown type..
        /// </summary>
        internal static string GrammarCompilerErrors_UnexpectedLiteralEntry {
            get {
                return ResourceManager.GetString("GrammarCompilerErrors_UnexpectedLiteralEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown reference was discovered. Identity references of type {0} are not supported..
        /// </summary>
        internal static string GrammarCompilerErrors_UnexpectedUndefinedEntry {
            get {
                return ResourceManager.GetString("GrammarCompilerErrors_UnexpectedUndefinedEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A duplicate entry was detected by its full set of terminals and non-terminals. Included is a listing of said duplications: {0}.
        /// </summary>
        internal static string GrammarCompilerWarnings_DuplicateDefinition {
            get {
                return ResourceManager.GetString("GrammarCompilerWarnings_DuplicateDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more terminals overlap in their finite automata&apos;s edge states.  This might increase the chances of an ambiguity if the edge of a rule ends on two or more of these symbols.  The list of offending symbols is below:
        ///    {0}.
        /// </summary>
        internal static string GrammarCompilerWarnings_LexicalAmbiguity {
            get {
                return ResourceManager.GetString("GrammarCompilerWarnings_LexicalAmbiguity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more terminals overlap in their finite automata&apos;s edge states.  This might increase the chances of an ambiguity if the edge of a rule ends on two or more of these symbols.  This specific combination of symbols was not observed in the analysis of the grammar.  The list of offending symbols is below:
        ///    {0}.
        /// </summary>
        internal static string GrammarCompilerWarnings_UnobservedLexicalAmbiguity {
            get {
                return ResourceManager.GetString("GrammarCompilerWarnings_UnobservedLexicalAmbiguity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add expression ({0}) to rule {1}.  {1} has not been defined..
        /// </summary>
        internal static string GrammarErrors_AddRuleTargetUndefined {
            get {
                return ResourceManager.GetString("GrammarErrors_AddRuleTargetUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term &apos;{0}&apos; is already defined..
        /// </summary>
        internal static string GrammarErrors_DuplicateTermDefined {
            get {
                return ResourceManager.GetString("GrammarErrors_DuplicateTermDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of dynamic arguments given did not group properly..
        /// </summary>
        internal static string GrammarErrors_DynamicArgumentCountError {
            get {
                return ResourceManager.GetString("GrammarErrors_DynamicArgumentCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected: &apos;{0}&apos;..
        /// </summary>
        internal static string GrammarParserErrors_Expected {
            get {
                return ResourceManager.GetString("GrammarParserErrors_Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected end of file..
        /// </summary>
        internal static string GrammarParserErrors_ExpectedEndOfFile {
            get {
                return ResourceManager.GetString("GrammarParserErrors_ExpectedEndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected end of line..
        /// </summary>
        internal static string GrammarParserErrors_ExpectedEndOfLine {
            get {
                return ResourceManager.GetString("GrammarParserErrors_ExpectedEndOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of supplied arguments for temlate &apos;{0}&apos; is invalid, expected {1}, but got {2}..
        /// </summary>
        internal static string GrammarParserErrors_FixedArgumentCountError {
            get {
                return ResourceManager.GetString("GrammarParserErrors_FixedArgumentCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include &apos;{0}&apos; was not found..
        /// </summary>
        internal static string GrammarParserErrors_IncludeFileNotFound {
            get {
                return ResourceManager.GetString("GrammarParserErrors_IncludeFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid escape sequence..
        /// </summary>
        internal static string GrammarParserErrors_InvalidEscape {
            get {
                return ResourceManager.GetString("GrammarParserErrors_InvalidEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must also be dynamic in length (&apos;+&apos;)..
        /// </summary>
        internal static string GrammarParserErrors_InvalidRepeatOptions {
            get {
                return ResourceManager.GetString("GrammarParserErrors_InvalidRepeatOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in grammar {1} is not a valid starting rule..
        /// </summary>
        internal static string GrammarParserErrors_InvalidStartDefined {
            get {
                return ResourceManager.GetString("GrammarParserErrors_InvalidStartDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The named token callout referenced is incorrect.  There are only two types of tokens that can be referenced directly: Literals of &apos;String&apos; or &apos;Char&apos; variety..
        /// </summary>
        internal static string GrammarParserErrors_InvalidTokenReference {
            get {
                return ResourceManager.GetString("GrammarParserErrors_InvalidTokenReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The grammar &apos;{0}&apos; has no start point defined..
        /// </summary>
        internal static string GrammarParserErrors_NoStartDefined {
            get {
                return ResourceManager.GetString("GrammarParserErrors_NoStartDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule &apos;{0}&apos; is a template and requires expression arguments to reference properly..
        /// </summary>
        internal static string GrammarParserErrors_RuleIsTemplate {
            get {
                return ResourceManager.GetString("GrammarParserErrors_RuleIsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule &apos;{0}&apos; is never used..
        /// </summary>
        internal static string GrammarParserErrors_RuleNeverUsed {
            get {
                return ResourceManager.GetString("GrammarParserErrors_RuleNeverUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule &apos;{0}&apos; is not a template rule.  Parametered usage is not needed or allowed..
        /// </summary>
        internal static string GrammarParserErrors_RuleNotTemplate {
            get {
                return ResourceManager.GetString("GrammarParserErrors_RuleNotTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined token or rule reference &apos;{0}&apos;..
        /// </summary>
        internal static string GrammarParserErrors_UndefinedRuleReference {
            get {
                return ResourceManager.GetString("GrammarParserErrors_UndefinedRuleReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined reference{0}..
        /// </summary>
        internal static string GrammarParserErrors_UndefinedTokenReference {
            get {
                return ResourceManager.GetString("GrammarParserErrors_UndefinedTokenReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected: &apos;{0}&apos;..
        /// </summary>
        internal static string GrammarParserErrors_Unexpected {
            get {
                return ResourceManager.GetString("GrammarParserErrors_Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file..
        /// </summary>
        internal static string GrammarParserErrors_UnexpectedEndOfFile {
            get {
                return ResourceManager.GetString("GrammarParserErrors_UnexpectedEndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of line..
        /// </summary>
        internal static string GrammarParserErrors_UnexpectedEndOfLine {
            get {
                return ResourceManager.GetString("GrammarParserErrors_UnexpectedEndOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown symbol &apos;{0}&apos;..
        /// </summary>
        internal static string GrammarParserErrors_UnknownSymbol {
            get {
                return ResourceManager.GetString("GrammarParserErrors_UnknownSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string IndexerName {
            get {
                return ResourceManager.GetString("IndexerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IsDefined target {0}: must have special expectancy of Rule..
        /// </summary>
        internal static string IsDefinedTemplateParameterMustExpectRule {
            get {
                return ResourceManager.GetString("IsDefinedTemplateParameterMustExpectRule", resourceCulture);
            }
        }
    }
}
