//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oilexer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Oilexer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as.
        /// </summary>
        internal static string CSharpKeyWord_02_As {
            get {
                return ResourceManager.GetString("CSharpKeyWord_02_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do.
        /// </summary>
        internal static string CSharpKeyWord_02_Do {
            get {
                return ResourceManager.GetString("CSharpKeyWord_02_Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if.
        /// </summary>
        internal static string CSharpKeyWord_02_If {
            get {
                return ResourceManager.GetString("CSharpKeyWord_02_If", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string CSharpKeyWord_02_In {
            get {
                return ResourceManager.GetString("CSharpKeyWord_02_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is.
        /// </summary>
        internal static string CSharpKeyWord_02_Is {
            get {
                return ResourceManager.GetString("CSharpKeyWord_02_Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        internal static string CSharpKeyWord_03_For {
            get {
                return ResourceManager.GetString("CSharpKeyWord_03_For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get.
        /// </summary>
        internal static string CSharpKeyWord_03_Get {
            get {
                return ResourceManager.GetString("CSharpKeyWord_03_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int.
        /// </summary>
        internal static string CSharpKeyWord_03_Int {
            get {
                return ResourceManager.GetString("CSharpKeyWord_03_Int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        internal static string CSharpKeyWord_03_New {
            get {
                return ResourceManager.GetString("CSharpKeyWord_03_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out.
        /// </summary>
        internal static string CSharpKeyWord_03_Out {
            get {
                return ResourceManager.GetString("CSharpKeyWord_03_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ref.
        /// </summary>
        internal static string CSharpKeyWord_03_Ref {
            get {
                return ResourceManager.GetString("CSharpKeyWord_03_Ref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set.
        /// </summary>
        internal static string CSharpKeyWord_03_Set {
            get {
                return ResourceManager.GetString("CSharpKeyWord_03_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to try.
        /// </summary>
        internal static string CSharpKeyWord_03_Try {
            get {
                return ResourceManager.GetString("CSharpKeyWord_03_Try", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to base.
        /// </summary>
        internal static string CSharpKeyWord_04_Base {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bool.
        /// </summary>
        internal static string CSharpKeyWord_04_Bool {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Bool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byte.
        /// </summary>
        internal static string CSharpKeyWord_04_Byte {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to case.
        /// </summary>
        internal static string CSharpKeyWord_04_Case {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to char.
        /// </summary>
        internal static string CSharpKeyWord_04_Char {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to else.
        /// </summary>
        internal static string CSharpKeyWord_04_Else {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Else", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enum.
        /// </summary>
        internal static string CSharpKeyWord_04_Enum {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to goto.
        /// </summary>
        internal static string CSharpKeyWord_04_Goto {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Goto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lock.
        /// </summary>
        internal static string CSharpKeyWord_04_Lock {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to long.
        /// </summary>
        internal static string CSharpKeyWord_04_Long {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null.
        /// </summary>
        internal static string CSharpKeyWord_04_Null {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this.
        /// </summary>
        internal static string CSharpKeyWord_04_This {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_This", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string CSharpKeyWord_04_True {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uint.
        /// </summary>
        internal static string CSharpKeyWord_04_Uint {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Uint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to void.
        /// </summary>
        internal static string CSharpKeyWord_04_Void {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Void", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to break.
        /// </summary>
        internal static string CSharpKeyWord_05_Break {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to catch.
        /// </summary>
        internal static string CSharpKeyWord_05_Catch {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Catch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class.
        /// </summary>
        internal static string CSharpKeyWord_05_Class {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to const.
        /// </summary>
        internal static string CSharpKeyWord_05_Const {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Const", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event.
        /// </summary>
        internal static string CSharpKeyWord_05_Event {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string CSharpKeyWord_05_False {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fixed.
        /// </summary>
        internal static string CSharpKeyWord_05_Fixed {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to float.
        /// </summary>
        internal static string CSharpKeyWord_05_Float {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sbyte.
        /// </summary>
        internal static string CSharpKeyWord_05_Sbyte {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Sbyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to short.
        /// </summary>
        internal static string CSharpKeyWord_05_Short {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to throw.
        /// </summary>
        internal static string CSharpKeyWord_05_Throw {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Throw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ulong.
        /// </summary>
        internal static string CSharpKeyWord_05_Ulong {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Ulong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using.
        /// </summary>
        internal static string CSharpKeyWord_05_Using {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to where.
        /// </summary>
        internal static string CSharpKeyWord_05_Where {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to while.
        /// </summary>
        internal static string CSharpKeyWord_05_While {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_While", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yield.
        /// </summary>
        internal static string CSharpKeyWord_05_Yield {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Yield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to double.
        /// </summary>
        internal static string CSharpKeyWord_06_Double {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extern.
        /// </summary>
        internal static string CSharpKeyWord_06_Extern {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Extern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object.
        /// </summary>
        internal static string CSharpKeyWord_06_Object {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to params.
        /// </summary>
        internal static string CSharpKeyWord_06_Params {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public.
        /// </summary>
        internal static string CSharpKeyWord_06_Public {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return.
        /// </summary>
        internal static string CSharpKeyWord_06_Return {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sealed.
        /// </summary>
        internal static string CSharpKeyWord_06_Sealed {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Sealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sizeof.
        /// </summary>
        internal static string CSharpKeyWord_06_Sizeof {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Sizeof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to static.
        /// </summary>
        internal static string CSharpKeyWord_06_Static {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string.
        /// </summary>
        internal static string CSharpKeyWord_06_String {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to struct.
        /// </summary>
        internal static string CSharpKeyWord_06_Struct {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Struct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch.
        /// </summary>
        internal static string CSharpKeyWord_06_Switch {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to typeof.
        /// </summary>
        internal static string CSharpKeyWord_06_Typeof {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Typeof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsafe.
        /// </summary>
        internal static string CSharpKeyWord_06_Unsafe {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Unsafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ushort.
        /// </summary>
        internal static string CSharpKeyWord_06_Ushort {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Ushort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checked.
        /// </summary>
        internal static string CSharpKeyWord_07_Checked {
            get {
                return ResourceManager.GetString("CSharpKeyWord_07_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decimal.
        /// </summary>
        internal static string CSharpKeyWord_07_Decimal {
            get {
                return ResourceManager.GetString("CSharpKeyWord_07_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        internal static string CSharpKeyWord_07_Default {
            get {
                return ResourceManager.GetString("CSharpKeyWord_07_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finally.
        /// </summary>
        internal static string CSharpKeyWord_07_Finally {
            get {
                return ResourceManager.GetString("CSharpKeyWord_07_Finally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to foreach.
        /// </summary>
        internal static string CSharpKeyWord_07_Foreach {
            get {
                return ResourceManager.GetString("CSharpKeyWord_07_Foreach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partial.
        /// </summary>
        internal static string CSharpKeyWord_07_Partial {
            get {
                return ResourceManager.GetString("CSharpKeyWord_07_Partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private.
        /// </summary>
        internal static string CSharpKeyWord_07_Private {
            get {
                return ResourceManager.GetString("CSharpKeyWord_07_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to virtual.
        /// </summary>
        internal static string CSharpKeyWord_07_Virtual {
            get {
                return ResourceManager.GetString("CSharpKeyWord_07_Virtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abstract.
        /// </summary>
        internal static string CSharpKeyWord_08_Abstract {
            get {
                return ResourceManager.GetString("CSharpKeyWord_08_Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue.
        /// </summary>
        internal static string CSharpKeyWord_08_Continue {
            get {
                return ResourceManager.GetString("CSharpKeyWord_08_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delegate.
        /// </summary>
        internal static string CSharpKeyWord_08_Delegate {
            get {
                return ResourceManager.GetString("CSharpKeyWord_08_Delegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to explicit.
        /// </summary>
        internal static string CSharpKeyWord_08_Explicit {
            get {
                return ResourceManager.GetString("CSharpKeyWord_08_Explicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to implicit.
        /// </summary>
        internal static string CSharpKeyWord_08_Implicit {
            get {
                return ResourceManager.GetString("CSharpKeyWord_08_Implicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal.
        /// </summary>
        internal static string CSharpKeyWord_08_Internal {
            get {
                return ResourceManager.GetString("CSharpKeyWord_08_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operator.
        /// </summary>
        internal static string CSharpKeyWord_08_Operator {
            get {
                return ResourceManager.GetString("CSharpKeyWord_08_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to override.
        /// </summary>
        internal static string CSharpKeyWord_08_Override {
            get {
                return ResourceManager.GetString("CSharpKeyWord_08_Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to readonly.
        /// </summary>
        internal static string CSharpKeyWord_08_Readonly {
            get {
                return ResourceManager.GetString("CSharpKeyWord_08_Readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volatile.
        /// </summary>
        internal static string CSharpKeyWord_08_Volatile {
            get {
                return ResourceManager.GetString("CSharpKeyWord_08_Volatile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __arglist.
        /// </summary>
        internal static string CSharpKeyWord_09___arglist {
            get {
                return ResourceManager.GetString("CSharpKeyWord_09___arglist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __makeref.
        /// </summary>
        internal static string CSharpKeyWord_09___makeref {
            get {
                return ResourceManager.GetString("CSharpKeyWord_09___makeref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __reftype.
        /// </summary>
        internal static string CSharpKeyWord_09___reftype {
            get {
                return ResourceManager.GetString("CSharpKeyWord_09___reftype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interface.
        /// </summary>
        internal static string CSharpKeyWord_09_Interface {
            get {
                return ResourceManager.GetString("CSharpKeyWord_09_Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace.
        /// </summary>
        internal static string CSharpKeyWord_09_Namespace {
            get {
                return ResourceManager.GetString("CSharpKeyWord_09_Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protected.
        /// </summary>
        internal static string CSharpKeyWord_09_Protected {
            get {
                return ResourceManager.GetString("CSharpKeyWord_09_Protected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unchecked.
        /// </summary>
        internal static string CSharpKeyWord_09_Unchecked {
            get {
                return ResourceManager.GetString("CSharpKeyWord_09_Unchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __refvalue.
        /// </summary>
        internal static string CSharpKeyWord_10___refvalue {
            get {
                return ResourceManager.GetString("CSharpKeyWord_10___refvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stackalloc.
        /// </summary>
        internal static string CSharpKeyWord_10_Stackalloc {
            get {
                return ResourceManager.GetString("CSharpKeyWord_10_Stackalloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OILParserAssembly.
        /// </summary>
        internal static string DefaultAssemblyName {
            get {
                return ResourceManager.GetString("DefaultAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnnamedGrammar.
        /// </summary>
        internal static string DefaultGrammarName {
            get {
                return ResourceManager.GetString("DefaultGrammarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OiLexer.
        /// </summary>
        internal static string DefaultLexerName {
            get {
                return ResourceManager.GetString("DefaultLexerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OilexerParser.
        /// </summary>
        internal static string DefaultParserName {
            get {
                return ResourceManager.GetString("DefaultParserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of dynamic arguments given did not group properly..
        /// </summary>
        internal static string GrammarErrors_DynamicArgumentCountError {
            get {
                return ResourceManager.GetString("GrammarErrors_DynamicArgumentCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected: &apos;{0}&apos;..
        /// </summary>
        internal static string GrammarParserErrors_Expected {
            get {
                return ResourceManager.GetString("GrammarParserErrors_Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected end of file..
        /// </summary>
        internal static string GrammarParserErrors_ExpectedEndOfFile {
            get {
                return ResourceManager.GetString("GrammarParserErrors_ExpectedEndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected end of line..
        /// </summary>
        internal static string GrammarParserErrors_ExpectedEndOfLine {
            get {
                return ResourceManager.GetString("GrammarParserErrors_ExpectedEndOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of supplied arguments for temlate {0}..
        /// </summary>
        internal static string GrammarParserErrors_FixedArgumentCountError {
            get {
                return ResourceManager.GetString("GrammarParserErrors_FixedArgumentCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include &apos;{0}&apos; was not found..
        /// </summary>
        internal static string GrammarParserErrors_IncludeFileNotFound {
            get {
                return ResourceManager.GetString("GrammarParserErrors_IncludeFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid escape sequence..
        /// </summary>
        internal static string GrammarParserErrors_InvalidEscape {
            get {
                return ResourceManager.GetString("GrammarParserErrors_InvalidEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must also be dynamic in length (&apos;+&apos;)..
        /// </summary>
        internal static string GrammarParserErrors_InvalidRepeatOptions {
            get {
                return ResourceManager.GetString("GrammarParserErrors_InvalidRepeatOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The grammar &apos;{0}&apos; has an invalid start point defined..
        /// </summary>
        internal static string GrammarParserErrors_InvalidStartDefined {
            get {
                return ResourceManager.GetString("GrammarParserErrors_InvalidStartDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The grammar &apos;{0}&apos; has no start point defined..
        /// </summary>
        internal static string GrammarParserErrors_NoStartDefined {
            get {
                return ResourceManager.GetString("GrammarParserErrors_NoStartDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule &apos;{0}&apos; is a template and requires expression arguments to reference properly..
        /// </summary>
        internal static string GrammarParserErrors_RuleIsTemplate {
            get {
                return ResourceManager.GetString("GrammarParserErrors_RuleIsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule &apos;{0}&apos; is never used..
        /// </summary>
        internal static string GrammarParserErrors_RuleNeverUsed {
            get {
                return ResourceManager.GetString("GrammarParserErrors_RuleNeverUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule &apos;{0}&apos; is not a template rule.  Parametered usage is not needed or allowed..
        /// </summary>
        internal static string GrammarParserErrors_RuleNotTemplate {
            get {
                return ResourceManager.GetString("GrammarParserErrors_RuleNotTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined token or rule reference &apos;{0}&apos;..
        /// </summary>
        internal static string GrammarParserErrors_UndefinedRuleReference {
            get {
                return ResourceManager.GetString("GrammarParserErrors_UndefinedRuleReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined reference &apos;{0}&apos;..
        /// </summary>
        internal static string GrammarParserErrors_UndefinedTokenReference {
            get {
                return ResourceManager.GetString("GrammarParserErrors_UndefinedTokenReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected: &apos;{0}&apos;..
        /// </summary>
        internal static string GrammarParserErrors_Unexpected {
            get {
                return ResourceManager.GetString("GrammarParserErrors_Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file..
        /// </summary>
        internal static string GrammarParserErrors_UnexpectedEndOfFile {
            get {
                return ResourceManager.GetString("GrammarParserErrors_UnexpectedEndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of line..
        /// </summary>
        internal static string GrammarParserErrors_UnexpectedEndOfLine {
            get {
                return ResourceManager.GetString("GrammarParserErrors_UnexpectedEndOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown symbol &apos;{0}&apos;..
        /// </summary>
        internal static string GrammarParserErrors_UnknownSymbol {
            get {
                return ResourceManager.GetString("GrammarParserErrors_UnknownSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string IndexerName {
            get {
                return ResourceManager.GetString("IndexerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Resources__.
        /// </summary>
        internal static string ResourcesAutoClassName {
            get {
                return ResourceManager.GetString("ResourcesAutoClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Resources__.
        /// </summary>
        internal static string ResourcesAutoClassName1 {
            get {
                return ResourceManager.GetString("ResourcesAutoClassName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As.
        /// </summary>
        internal static string VBKeyWord_02_As {
            get {
                return ResourceManager.GetString("VBKeyWord_02_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        internal static string VBKeyWord_02_Do {
            get {
                return ResourceManager.GetString("VBKeyWord_02_Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If.
        /// </summary>
        internal static string VBKeyWord_02_If {
            get {
                return ResourceManager.GetString("VBKeyWord_02_If", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        internal static string VBKeyWord_02_In {
            get {
                return ResourceManager.GetString("VBKeyWord_02_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is.
        /// </summary>
        internal static string VBKeyWord_02_Is {
            get {
                return ResourceManager.GetString("VBKeyWord_02_Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        internal static string VBKeyWord_02_Me {
            get {
                return ResourceManager.GetString("VBKeyWord_02_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of.
        /// </summary>
        internal static string VBKeyWord_02_Of {
            get {
                return ResourceManager.GetString("VBKeyWord_02_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string VBKeyWord_02_On {
            get {
                return ResourceManager.GetString("VBKeyWord_02_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string VBKeyWord_02_Or {
            get {
                return ResourceManager.GetString("VBKeyWord_02_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string VBKeyWord_02_To {
            get {
                return ResourceManager.GetString("VBKeyWord_02_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        internal static string VBKeyWord_03_And {
            get {
                return ResourceManager.GetString("VBKeyWord_03_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dim.
        /// </summary>
        internal static string VBKeyWord_03_Dim {
            get {
                return ResourceManager.GetString("VBKeyWord_03_Dim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string VBKeyWord_03_End {
            get {
                return ResourceManager.GetString("VBKeyWord_03_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For.
        /// </summary>
        internal static string VBKeyWord_03_For {
            get {
                return ResourceManager.GetString("VBKeyWord_03_For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get.
        /// </summary>
        internal static string VBKeyWord_03_Get {
            get {
                return ResourceManager.GetString("VBKeyWord_03_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let.
        /// </summary>
        internal static string VBKeyWord_03_Let {
            get {
                return ResourceManager.GetString("VBKeyWord_03_Let", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lib.
        /// </summary>
        internal static string VBKeyWord_03_Lib {
            get {
                return ResourceManager.GetString("VBKeyWord_03_Lib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod.
        /// </summary>
        internal static string VBKeyWord_03_Mod {
            get {
                return ResourceManager.GetString("VBKeyWord_03_Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string VBKeyWord_03_New {
            get {
                return ResourceManager.GetString("VBKeyWord_03_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not.
        /// </summary>
        internal static string VBKeyWord_03_Not {
            get {
                return ResourceManager.GetString("VBKeyWord_03_Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rem.
        /// </summary>
        internal static string VBKeyWord_03_Rem {
            get {
                return ResourceManager.GetString("VBKeyWord_03_Rem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string VBKeyWord_03_Set {
            get {
                return ResourceManager.GetString("VBKeyWord_03_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub.
        /// </summary>
        internal static string VBKeyWord_03_Sub {
            get {
                return ResourceManager.GetString("VBKeyWord_03_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try.
        /// </summary>
        internal static string VBKeyWord_03_Try {
            get {
                return ResourceManager.GetString("VBKeyWord_03_Try", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XOr.
        /// </summary>
        internal static string VBKeyWord_03_XOr {
            get {
                return ResourceManager.GetString("VBKeyWord_03_XOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansi.
        /// </summary>
        internal static string VBKeyWord_04_Ansi {
            get {
                return ResourceManager.GetString("VBKeyWord_04_Ansi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string VBKeyWord_04_Auto {
            get {
                return ResourceManager.GetString("VBKeyWord_04_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte.
        /// </summary>
        internal static string VBKeyWord_04_Byte {
            get {
                return ResourceManager.GetString("VBKeyWord_04_Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        internal static string VBKeyWord_04_Call {
            get {
                return ResourceManager.GetString("VBKeyWord_04_Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case.
        /// </summary>
        internal static string VBKeyWord_04_Case {
            get {
                return ResourceManager.GetString("VBKeyWord_04_Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDbl.
        /// </summary>
        internal static string VBKeyWord_04_CDbl {
            get {
                return ResourceManager.GetString("VBKeyWord_04_CDbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDec.
        /// </summary>
        internal static string VBKeyWord_04_CDec {
            get {
                return ResourceManager.GetString("VBKeyWord_04_CDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Char.
        /// </summary>
        internal static string VBKeyWord_04_Char {
            get {
                return ResourceManager.GetString("VBKeyWord_04_Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CInt.
        /// </summary>
        internal static string VBKeyWord_04_CInt {
            get {
                return ResourceManager.GetString("VBKeyWord_04_CInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLng.
        /// </summary>
        internal static string VBKeyWord_04_CLng {
            get {
                return ResourceManager.GetString("VBKeyWord_04_CLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CObj.
        /// </summary>
        internal static string VBKeyWord_04_CObj {
            get {
                return ResourceManager.GetString("VBKeyWord_04_CObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSng.
        /// </summary>
        internal static string VBKeyWord_04_CSng {
            get {
                return ResourceManager.GetString("VBKeyWord_04_CSng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CStr.
        /// </summary>
        internal static string VBKeyWord_04_CStr {
            get {
                return ResourceManager.GetString("VBKeyWord_04_CStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string VBKeyWord_04_Date {
            get {
                return ResourceManager.GetString("VBKeyWord_04_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each.
        /// </summary>
        internal static string VBKeyWord_04_Each {
            get {
                return ResourceManager.GetString("VBKeyWord_04_Each", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Else.
        /// </summary>
        internal static string VBKeyWord_04_Else {
            get {
                return ResourceManager.GetString("VBKeyWord_04_Else", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum.
        /// </summary>
        internal static string VBKeyWord_04_Enum {
            get {
                return ResourceManager.GetString("VBKeyWord_04_Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string VBKeyWord_04_Exit {
            get {
                return ResourceManager.GetString("VBKeyWord_04_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoTo.
        /// </summary>
        internal static string VBKeyWord_04_GoTo {
            get {
                return ResourceManager.GetString("VBKeyWord_04_GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        internal static string VBKeyWord_04_Like {
            get {
                return ResourceManager.GetString("VBKeyWord_04_Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long.
        /// </summary>
        internal static string VBKeyWord_04_Long {
            get {
                return ResourceManager.GetString("VBKeyWord_04_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop.
        /// </summary>
        internal static string VBKeyWord_04_Loop {
            get {
                return ResourceManager.GetString("VBKeyWord_04_Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string VBKeyWord_04_Next {
            get {
                return ResourceManager.GetString("VBKeyWord_04_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        internal static string VBKeyWord_04_Step {
            get {
                return ResourceManager.GetString("VBKeyWord_04_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string VBKeyWord_04_Stop {
            get {
                return ResourceManager.GetString("VBKeyWord_04_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then.
        /// </summary>
        internal static string VBKeyWord_04_Then {
            get {
                return ResourceManager.GetString("VBKeyWord_04_Then", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string VBKeyWord_04_True {
            get {
                return ResourceManager.GetString("VBKeyWord_04_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wend.
        /// </summary>
        internal static string VBKeyWord_04_Wend {
            get {
                return ResourceManager.GetString("VBKeyWord_04_Wend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When.
        /// </summary>
        internal static string VBKeyWord_04_When {
            get {
                return ResourceManager.GetString("VBKeyWord_04_When", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With.
        /// </summary>
        internal static string VBKeyWord_04_With {
            get {
                return ResourceManager.GetString("VBKeyWord_04_With", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        internal static string VBKeyWord_05_Alias {
            get {
                return ResourceManager.GetString("VBKeyWord_05_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ByRef.
        /// </summary>
        internal static string VBKeyWord_05_ByRef {
            get {
                return ResourceManager.GetString("VBKeyWord_05_ByRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ByVal.
        /// </summary>
        internal static string VBKeyWord_05_ByVal {
            get {
                return ResourceManager.GetString("VBKeyWord_05_ByVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch.
        /// </summary>
        internal static string VBKeyWord_05_Catch {
            get {
                return ResourceManager.GetString("VBKeyWord_05_Catch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBool.
        /// </summary>
        internal static string VBKeyWord_05_CBool {
            get {
                return ResourceManager.GetString("VBKeyWord_05_CBool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CByte.
        /// </summary>
        internal static string VBKeyWord_05_CByte {
            get {
                return ResourceManager.GetString("VBKeyWord_05_CByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CChar.
        /// </summary>
        internal static string VBKeyWord_05_CChar {
            get {
                return ResourceManager.GetString("VBKeyWord_05_CChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDate.
        /// </summary>
        internal static string VBKeyWord_05_CDate {
            get {
                return ResourceManager.GetString("VBKeyWord_05_CDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string VBKeyWord_05_Class {
            get {
                return ResourceManager.GetString("VBKeyWord_05_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Const.
        /// </summary>
        internal static string VBKeyWord_05_Const {
            get {
                return ResourceManager.GetString("VBKeyWord_05_Const", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CType.
        /// </summary>
        internal static string VBKeyWord_05_CType {
            get {
                return ResourceManager.GetString("VBKeyWord_05_CType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUInt.
        /// </summary>
        internal static string VBKeyWord_05_CUInt {
            get {
                return ResourceManager.GetString("VBKeyWord_05_CUInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CULng.
        /// </summary>
        internal static string VBKeyWord_05_CULng {
            get {
                return ResourceManager.GetString("VBKeyWord_05_CULng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndIf.
        /// </summary>
        internal static string VBKeyWord_05_EndIf {
            get {
                return ResourceManager.GetString("VBKeyWord_05_EndIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase.
        /// </summary>
        internal static string VBKeyWord_05_Erase {
            get {
                return ResourceManager.GetString("VBKeyWord_05_Erase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string VBKeyWord_05_Error {
            get {
                return ResourceManager.GetString("VBKeyWord_05_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string VBKeyWord_05_Event {
            get {
                return ResourceManager.GetString("VBKeyWord_05_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string VBKeyWord_05_False {
            get {
                return ResourceManager.GetString("VBKeyWord_05_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoSub.
        /// </summary>
        internal static string VBKeyWord_05_GoSub {
            get {
                return ResourceManager.GetString("VBKeyWord_05_GoSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsNot.
        /// </summary>
        internal static string VBKeyWord_05_IsNot {
            get {
                return ResourceManager.GetString("VBKeyWord_05_IsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReDim.
        /// </summary>
        internal static string VBKeyWord_05_ReDim {
            get {
                return ResourceManager.GetString("VBKeyWord_05_ReDim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SByte.
        /// </summary>
        internal static string VBKeyWord_05_SByte {
            get {
                return ResourceManager.GetString("VBKeyWord_05_SByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short.
        /// </summary>
        internal static string VBKeyWord_05_Short {
            get {
                return ResourceManager.GetString("VBKeyWord_05_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw.
        /// </summary>
        internal static string VBKeyWord_05_Throw {
            get {
                return ResourceManager.GetString("VBKeyWord_05_Throw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ULong.
        /// </summary>
        internal static string VBKeyWord_05_ULong {
            get {
                return ResourceManager.GetString("VBKeyWord_05_ULong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until.
        /// </summary>
        internal static string VBKeyWord_05_Until {
            get {
                return ResourceManager.GetString("VBKeyWord_05_Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using.
        /// </summary>
        internal static string VBKeyWord_05_Using {
            get {
                return ResourceManager.GetString("VBKeyWord_05_Using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While.
        /// </summary>
        internal static string VBKeyWord_05_While {
            get {
                return ResourceManager.GetString("VBKeyWord_05_While", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSByte.
        /// </summary>
        internal static string VBKeyWord_06_CSByte {
            get {
                return ResourceManager.GetString("VBKeyWord_06_CSByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CShort.
        /// </summary>
        internal static string VBKeyWord_06_CShort {
            get {
                return ResourceManager.GetString("VBKeyWord_06_CShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double.
        /// </summary>
        internal static string VBKeyWord_06_Double {
            get {
                return ResourceManager.GetString("VBKeyWord_06_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElseIf.
        /// </summary>
        internal static string VBKeyWord_06_ElseIf {
            get {
                return ResourceManager.GetString("VBKeyWord_06_ElseIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend.
        /// </summary>
        internal static string VBKeyWord_06_Friend {
            get {
                return ResourceManager.GetString("VBKeyWord_06_Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        internal static string VBKeyWord_06_Global {
            get {
                return ResourceManager.GetString("VBKeyWord_06_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        internal static string VBKeyWord_06_Module {
            get {
                return ResourceManager.GetString("VBKeyWord_06_Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyBase.
        /// </summary>
        internal static string VBKeyWord_06_MyBase {
            get {
                return ResourceManager.GetString("VBKeyWord_06_MyBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string VBKeyWord_06_Object {
            get {
                return ResourceManager.GetString("VBKeyWord_06_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        internal static string VBKeyWord_06_Option {
            get {
                return ResourceManager.GetString("VBKeyWord_06_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrElse.
        /// </summary>
        internal static string VBKeyWord_06_OrElse {
            get {
                return ResourceManager.GetString("VBKeyWord_06_OrElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string VBKeyWord_06_Public {
            get {
                return ResourceManager.GetString("VBKeyWord_06_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string VBKeyWord_06_Resume {
            get {
                return ResourceManager.GetString("VBKeyWord_06_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string VBKeyWord_06_Return {
            get {
                return ResourceManager.GetString("VBKeyWord_06_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string VBKeyWord_06_Select {
            get {
                return ResourceManager.GetString("VBKeyWord_06_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        internal static string VBKeyWord_06_Shared {
            get {
                return ResourceManager.GetString("VBKeyWord_06_Shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        internal static string VBKeyWord_06_Single {
            get {
                return ResourceManager.GetString("VBKeyWord_06_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static.
        /// </summary>
        internal static string VBKeyWord_06_Static {
            get {
                return ResourceManager.GetString("VBKeyWord_06_Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string VBKeyWord_06_String {
            get {
                return ResourceManager.GetString("VBKeyWord_06_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeOf.
        /// </summary>
        internal static string VBKeyWord_06_TypeOf {
            get {
                return ResourceManager.GetString("VBKeyWord_06_TypeOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UShort.
        /// </summary>
        internal static string VBKeyWord_06_UShort {
            get {
                return ResourceManager.GetString("VBKeyWord_06_UShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AndAlso.
        /// </summary>
        internal static string VBKeyWord_07_AndAlso {
            get {
                return ResourceManager.GetString("VBKeyWord_07_AndAlso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        internal static string VBKeyWord_07_Boolean {
            get {
                return ResourceManager.GetString("VBKeyWord_07_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUShort.
        /// </summary>
        internal static string VBKeyWord_07_CUShort {
            get {
                return ResourceManager.GetString("VBKeyWord_07_CUShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        internal static string VBKeyWord_07_Decimal {
            get {
                return ResourceManager.GetString("VBKeyWord_07_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare.
        /// </summary>
        internal static string VBKeyWord_07_Declare {
            get {
                return ResourceManager.GetString("VBKeyWord_07_Declare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string VBKeyWord_07_Default {
            get {
                return ResourceManager.GetString("VBKeyWord_07_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finally.
        /// </summary>
        internal static string VBKeyWord_07_Finally {
            get {
                return ResourceManager.GetString("VBKeyWord_07_Finally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetType.
        /// </summary>
        internal static string VBKeyWord_07_GetType {
            get {
                return ResourceManager.GetString("VBKeyWord_07_GetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handles.
        /// </summary>
        internal static string VBKeyWord_07_Handles {
            get {
                return ResourceManager.GetString("VBKeyWord_07_Handles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports.
        /// </summary>
        internal static string VBKeyWord_07_Imports {
            get {
                return ResourceManager.GetString("VBKeyWord_07_Imports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        internal static string VBKeyWord_07_Integer {
            get {
                return ResourceManager.GetString("VBKeyWord_07_Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyClass.
        /// </summary>
        internal static string VBKeyWord_07_MyClass {
            get {
                return ResourceManager.GetString("VBKeyWord_07_MyClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        internal static string VBKeyWord_07_Nothing {
            get {
                return ResourceManager.GetString("VBKeyWord_07_Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial.
        /// </summary>
        internal static string VBKeyWord_07_Partial {
            get {
                return ResourceManager.GetString("VBKeyWord_07_Partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string VBKeyWord_07_Private {
            get {
                return ResourceManager.GetString("VBKeyWord_07_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadows.
        /// </summary>
        internal static string VBKeyWord_07_Shadows {
            get {
                return ResourceManager.GetString("VBKeyWord_07_Shadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TryCast.
        /// </summary>
        internal static string VBKeyWord_07_TryCast {
            get {
                return ResourceManager.GetString("VBKeyWord_07_TryCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode.
        /// </summary>
        internal static string VBKeyWord_07_Unicode {
            get {
                return ResourceManager.GetString("VBKeyWord_07_Unicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant.
        /// </summary>
        internal static string VBKeyWord_07_Variant {
            get {
                return ResourceManager.GetString("VBKeyWord_07_Variant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly.
        /// </summary>
        internal static string VBKeyWord_08_Assembly {
            get {
                return ResourceManager.GetString("VBKeyWord_08_Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string VBKeyWord_08_Continue {
            get {
                return ResourceManager.GetString("VBKeyWord_08_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate.
        /// </summary>
        internal static string VBKeyWord_08_Delegate {
            get {
                return ResourceManager.GetString("VBKeyWord_08_Delegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string VBKeyWord_08_Function {
            get {
                return ResourceManager.GetString("VBKeyWord_08_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherits.
        /// </summary>
        internal static string VBKeyWord_08_Inherits {
            get {
                return ResourceManager.GetString("VBKeyWord_08_Inherits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        internal static string VBKeyWord_08_Operator {
            get {
                return ResourceManager.GetString("VBKeyWord_08_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        internal static string VBKeyWord_08_Optional {
            get {
                return ResourceManager.GetString("VBKeyWord_08_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve.
        /// </summary>
        internal static string VBKeyWord_08_Preserve {
            get {
                return ResourceManager.GetString("VBKeyWord_08_Preserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string VBKeyWord_08_Property {
            get {
                return ResourceManager.GetString("VBKeyWord_08_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadOnly.
        /// </summary>
        internal static string VBKeyWord_08_ReadOnly {
            get {
                return ResourceManager.GetString("VBKeyWord_08_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncLock.
        /// </summary>
        internal static string VBKeyWord_08_SyncLock {
            get {
                return ResourceManager.GetString("VBKeyWord_08_SyncLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UInteger.
        /// </summary>
        internal static string VBKeyWord_08_UInteger {
            get {
                return ResourceManager.GetString("VBKeyWord_08_UInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widening.
        /// </summary>
        internal static string VBKeyWord_08_Widening {
            get {
                return ResourceManager.GetString("VBKeyWord_08_Widening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressOf.
        /// </summary>
        internal static string VBKeyWord_09_AddressOf {
            get {
                return ResourceManager.GetString("VBKeyWord_09_AddressOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        internal static string VBKeyWord_09_Interface {
            get {
                return ResourceManager.GetString("VBKeyWord_09_Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        internal static string VBKeyWord_09_Namespace {
            get {
                return ResourceManager.GetString("VBKeyWord_09_Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrowing.
        /// </summary>
        internal static string VBKeyWord_09_Narrowing {
            get {
                return ResourceManager.GetString("VBKeyWord_09_Narrowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overloads.
        /// </summary>
        internal static string VBKeyWord_09_Overloads {
            get {
                return ResourceManager.GetString("VBKeyWord_09_Overloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overrides.
        /// </summary>
        internal static string VBKeyWord_09_Overrides {
            get {
                return ResourceManager.GetString("VBKeyWord_09_Overrides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected.
        /// </summary>
        internal static string VBKeyWord_09_Protected {
            get {
                return ResourceManager.GetString("VBKeyWord_09_Protected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure.
        /// </summary>
        internal static string VBKeyWord_09_Structure {
            get {
                return ResourceManager.GetString("VBKeyWord_09_Structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriteOnly.
        /// </summary>
        internal static string VBKeyWord_09_WriteOnly {
            get {
                return ResourceManager.GetString("VBKeyWord_09_WriteOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddHandler.
        /// </summary>
        internal static string VBKeyWord_10_AddHandler {
            get {
                return ResourceManager.GetString("VBKeyWord_10_AddHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectCast.
        /// </summary>
        internal static string VBKeyWord_10_DirectCast {
            get {
                return ResourceManager.GetString("VBKeyWord_10_DirectCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implements.
        /// </summary>
        internal static string VBKeyWord_10_Implements {
            get {
                return ResourceManager.GetString("VBKeyWord_10_Implements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParamArray.
        /// </summary>
        internal static string VBKeyWord_10_ParamArray {
            get {
                return ResourceManager.GetString("VBKeyWord_10_ParamArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RaiseEvent.
        /// </summary>
        internal static string VBKeyWord_10_RaiseEvent {
            get {
                return ResourceManager.GetString("VBKeyWord_10_RaiseEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WithEvents.
        /// </summary>
        internal static string VBKeyWord_10_WithEvents {
            get {
                return ResourceManager.GetString("VBKeyWord_10_WithEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MustInherit.
        /// </summary>
        internal static string VBKeyWord_11_MustInherit {
            get {
                return ResourceManager.GetString("VBKeyWord_11_MustInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overridable.
        /// </summary>
        internal static string VBKeyWord_11_Overridable {
            get {
                return ResourceManager.GetString("VBKeyWord_11_Overridable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveHandler.
        /// </summary>
        internal static string VBKeyWord_13_RemoveHandler {
            get {
                return ResourceManager.GetString("VBKeyWord_13_RemoveHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class_Finalize.
        /// </summary>
        internal static string VBKeyWord_14_Class_Finalize {
            get {
                return ResourceManager.GetString("VBKeyWord_14_Class_Finalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotInheritable.
        /// </summary>
        internal static string VBKeyWord_14_NotInheritable {
            get {
                return ResourceManager.GetString("VBKeyWord_14_NotInheritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotOverridable.
        /// </summary>
        internal static string VBKeyWord_14_NotOverridable {
            get {
                return ResourceManager.GetString("VBKeyWord_14_NotOverridable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class_Initialize.
        /// </summary>
        internal static string VBKeyWord_16_Class_Initialize {
            get {
                return ResourceManager.GetString("VBKeyWord_16_Class_Initialize", resourceCulture);
            }
        }
    }
}
