//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oilexer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Oilexer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as.
        /// </summary>
        internal static string CSharpKeyWord_02_As {
            get {
                return ResourceManager.GetString("CSharpKeyWord_02_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do.
        /// </summary>
        internal static string CSharpKeyWord_02_Do {
            get {
                return ResourceManager.GetString("CSharpKeyWord_02_Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if.
        /// </summary>
        internal static string CSharpKeyWord_02_If {
            get {
                return ResourceManager.GetString("CSharpKeyWord_02_If", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string CSharpKeyWord_02_In {
            get {
                return ResourceManager.GetString("CSharpKeyWord_02_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is.
        /// </summary>
        internal static string CSharpKeyWord_02_Is {
            get {
                return ResourceManager.GetString("CSharpKeyWord_02_Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        internal static string CSharpKeyWord_03_For {
            get {
                return ResourceManager.GetString("CSharpKeyWord_03_For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get.
        /// </summary>
        internal static string CSharpKeyWord_03_Get {
            get {
                return ResourceManager.GetString("CSharpKeyWord_03_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int.
        /// </summary>
        internal static string CSharpKeyWord_03_Int {
            get {
                return ResourceManager.GetString("CSharpKeyWord_03_Int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        internal static string CSharpKeyWord_03_New {
            get {
                return ResourceManager.GetString("CSharpKeyWord_03_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out.
        /// </summary>
        internal static string CSharpKeyWord_03_Out {
            get {
                return ResourceManager.GetString("CSharpKeyWord_03_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ref.
        /// </summary>
        internal static string CSharpKeyWord_03_Ref {
            get {
                return ResourceManager.GetString("CSharpKeyWord_03_Ref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set.
        /// </summary>
        internal static string CSharpKeyWord_03_Set {
            get {
                return ResourceManager.GetString("CSharpKeyWord_03_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to try.
        /// </summary>
        internal static string CSharpKeyWord_03_Try {
            get {
                return ResourceManager.GetString("CSharpKeyWord_03_Try", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to base.
        /// </summary>
        internal static string CSharpKeyWord_04_Base {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bool.
        /// </summary>
        internal static string CSharpKeyWord_04_Bool {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Bool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byte.
        /// </summary>
        internal static string CSharpKeyWord_04_Byte {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to case.
        /// </summary>
        internal static string CSharpKeyWord_04_Case {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to char.
        /// </summary>
        internal static string CSharpKeyWord_04_Char {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to else.
        /// </summary>
        internal static string CSharpKeyWord_04_Else {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Else", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enum.
        /// </summary>
        internal static string CSharpKeyWord_04_Enum {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to goto.
        /// </summary>
        internal static string CSharpKeyWord_04_Goto {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Goto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lock.
        /// </summary>
        internal static string CSharpKeyWord_04_Lock {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to long.
        /// </summary>
        internal static string CSharpKeyWord_04_Long {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null.
        /// </summary>
        internal static string CSharpKeyWord_04_Null {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this.
        /// </summary>
        internal static string CSharpKeyWord_04_This {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_This", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string CSharpKeyWord_04_True {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uint.
        /// </summary>
        internal static string CSharpKeyWord_04_Uint {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Uint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to void.
        /// </summary>
        internal static string CSharpKeyWord_04_Void {
            get {
                return ResourceManager.GetString("CSharpKeyWord_04_Void", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to break.
        /// </summary>
        internal static string CSharpKeyWord_05_Break {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to catch.
        /// </summary>
        internal static string CSharpKeyWord_05_Catch {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Catch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class.
        /// </summary>
        internal static string CSharpKeyWord_05_Class {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to const.
        /// </summary>
        internal static string CSharpKeyWord_05_Const {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Const", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event.
        /// </summary>
        internal static string CSharpKeyWord_05_Event {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string CSharpKeyWord_05_False {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fixed.
        /// </summary>
        internal static string CSharpKeyWord_05_Fixed {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to float.
        /// </summary>
        internal static string CSharpKeyWord_05_Float {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sbyte.
        /// </summary>
        internal static string CSharpKeyWord_05_Sbyte {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Sbyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to short.
        /// </summary>
        internal static string CSharpKeyWord_05_Short {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to throw.
        /// </summary>
        internal static string CSharpKeyWord_05_Throw {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Throw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ulong.
        /// </summary>
        internal static string CSharpKeyWord_05_Ulong {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Ulong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using.
        /// </summary>
        internal static string CSharpKeyWord_05_Using {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to where.
        /// </summary>
        internal static string CSharpKeyWord_05_Where {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to while.
        /// </summary>
        internal static string CSharpKeyWord_05_While {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_While", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yield.
        /// </summary>
        internal static string CSharpKeyWord_05_Yield {
            get {
                return ResourceManager.GetString("CSharpKeyWord_05_Yield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to double.
        /// </summary>
        internal static string CSharpKeyWord_06_Double {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extern.
        /// </summary>
        internal static string CSharpKeyWord_06_Extern {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Extern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object.
        /// </summary>
        internal static string CSharpKeyWord_06_Object {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to params.
        /// </summary>
        internal static string CSharpKeyWord_06_Params {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public.
        /// </summary>
        internal static string CSharpKeyWord_06_Public {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return.
        /// </summary>
        internal static string CSharpKeyWord_06_Return {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sealed.
        /// </summary>
        internal static string CSharpKeyWord_06_Sealed {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Sealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sizeof.
        /// </summary>
        internal static string CSharpKeyWord_06_Sizeof {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Sizeof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to static.
        /// </summary>
        internal static string CSharpKeyWord_06_Static {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string.
        /// </summary>
        internal static string CSharpKeyWord_06_String {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to struct.
        /// </summary>
        internal static string CSharpKeyWord_06_Struct {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Struct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch.
        /// </summary>
        internal static string CSharpKeyWord_06_Switch {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to typeof.
        /// </summary>
        internal static string CSharpKeyWord_06_Typeof {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Typeof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsafe.
        /// </summary>
        internal static string CSharpKeyWord_06_Unsafe {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Unsafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ushort.
        /// </summary>
        internal static string CSharpKeyWord_06_Ushort {
            get {
                return ResourceManager.GetString("CSharpKeyWord_06_Ushort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checked.
        /// </summary>
        internal static string CSharpKeyWord_07_Checked {
            get {
                return ResourceManager.GetString("CSharpKeyWord_07_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decimal.
        /// </summary>
        internal static string CSharpKeyWord_07_Decimal {
            get {
                return ResourceManager.GetString("CSharpKeyWord_07_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        internal static string CSharpKeyWord_07_Default {
            get {
                return ResourceManager.GetString("CSharpKeyWord_07_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finally.
        /// </summary>
        internal static string CSharpKeyWord_07_Finally {
            get {
                return ResourceManager.GetString("CSharpKeyWord_07_Finally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to foreach.
        /// </summary>
        internal static string CSharpKeyWord_07_Foreach {
            get {
                return ResourceManager.GetString("CSharpKeyWord_07_Foreach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partial.
        /// </summary>
        internal static string CSharpKeyWord_07_Partial {
            get {
                return ResourceManager.GetString("CSharpKeyWord_07_Partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private.
        /// </summary>
        internal static string CSharpKeyWord_07_Private {
            get {
                return ResourceManager.GetString("CSharpKeyWord_07_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to virtual.
        /// </summary>
        internal static string CSharpKeyWord_07_Virtual {
            get {
                return ResourceManager.GetString("CSharpKeyWord_07_Virtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abstract.
        /// </summary>
        internal static string CSharpKeyWord_08_Abstract {
            get {
                return ResourceManager.GetString("CSharpKeyWord_08_Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue.
        /// </summary>
        internal static string CSharpKeyWord_08_Continue {
            get {
                return ResourceManager.GetString("CSharpKeyWord_08_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delegate.
        /// </summary>
        internal static string CSharpKeyWord_08_Delegate {
            get {
                return ResourceManager.GetString("CSharpKeyWord_08_Delegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to explicit.
        /// </summary>
        internal static string CSharpKeyWord_08_Explicit {
            get {
                return ResourceManager.GetString("CSharpKeyWord_08_Explicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to implicit.
        /// </summary>
        internal static string CSharpKeyWord_08_Implicit {
            get {
                return ResourceManager.GetString("CSharpKeyWord_08_Implicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal.
        /// </summary>
        internal static string CSharpKeyWord_08_Internal {
            get {
                return ResourceManager.GetString("CSharpKeyWord_08_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operator.
        /// </summary>
        internal static string CSharpKeyWord_08_Operator {
            get {
                return ResourceManager.GetString("CSharpKeyWord_08_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to override.
        /// </summary>
        internal static string CSharpKeyWord_08_Override {
            get {
                return ResourceManager.GetString("CSharpKeyWord_08_Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to readonly.
        /// </summary>
        internal static string CSharpKeyWord_08_Readonly {
            get {
                return ResourceManager.GetString("CSharpKeyWord_08_Readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volatile.
        /// </summary>
        internal static string CSharpKeyWord_08_Volatile {
            get {
                return ResourceManager.GetString("CSharpKeyWord_08_Volatile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __arglist.
        /// </summary>
        internal static string CSharpKeyWord_09___arglist {
            get {
                return ResourceManager.GetString("CSharpKeyWord_09___arglist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __makeref.
        /// </summary>
        internal static string CSharpKeyWord_09___makeref {
            get {
                return ResourceManager.GetString("CSharpKeyWord_09___makeref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __reftype.
        /// </summary>
        internal static string CSharpKeyWord_09___reftype {
            get {
                return ResourceManager.GetString("CSharpKeyWord_09___reftype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interface.
        /// </summary>
        internal static string CSharpKeyWord_09_Interface {
            get {
                return ResourceManager.GetString("CSharpKeyWord_09_Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace.
        /// </summary>
        internal static string CSharpKeyWord_09_Namespace {
            get {
                return ResourceManager.GetString("CSharpKeyWord_09_Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protected.
        /// </summary>
        internal static string CSharpKeyWord_09_Protected {
            get {
                return ResourceManager.GetString("CSharpKeyWord_09_Protected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unchecked.
        /// </summary>
        internal static string CSharpKeyWord_09_Unchecked {
            get {
                return ResourceManager.GetString("CSharpKeyWord_09_Unchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __refvalue.
        /// </summary>
        internal static string CSharpKeyWord_10___refvalue {
            get {
                return ResourceManager.GetString("CSharpKeyWord_10___refvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stackalloc.
        /// </summary>
        internal static string CSharpKeyWord_10_Stackalloc {
            get {
                return ResourceManager.GetString("CSharpKeyWord_10_Stackalloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OILParserAssembly.
        /// </summary>
        internal static string DefaultAssemblyName {
            get {
                return ResourceManager.GetString("DefaultAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnnamedGrammar.
        /// </summary>
        internal static string DefaultGrammarName {
            get {
                return ResourceManager.GetString("DefaultGrammarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OiLexer.
        /// </summary>
        internal static string DefaultLexerName {
            get {
                return ResourceManager.GetString("DefaultLexerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OilexerParser.
        /// </summary>
        internal static string DefaultParserName {
            get {
                return ResourceManager.GetString("DefaultParserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of dynamic arguments given did not group properly..
        /// </summary>
        internal static string GrammarErrors_DynamicArgumentCountError {
            get {
                return ResourceManager.GetString("GrammarErrors_DynamicArgumentCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected: &apos;{0}&apos;..
        /// </summary>
        internal static string GrammarParserErrors_Expected {
            get {
                return ResourceManager.GetString("GrammarParserErrors_Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected end of file..
        /// </summary>
        internal static string GrammarParserErrors_ExpectedEndOfFile {
            get {
                return ResourceManager.GetString("GrammarParserErrors_ExpectedEndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected end of line..
        /// </summary>
        internal static string GrammarParserErrors_ExpectedEndOfLine {
            get {
                return ResourceManager.GetString("GrammarParserErrors_ExpectedEndOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of supplied arguments for temlate {0}..
        /// </summary>
        internal static string GrammarParserErrors_FixedArgumentCountError {
            get {
                return ResourceManager.GetString("GrammarParserErrors_FixedArgumentCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include &apos;{0}&apos; was not found..
        /// </summary>
        internal static string GrammarParserErrors_IncludeFileNotFound {
            get {
                return ResourceManager.GetString("GrammarParserErrors_IncludeFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid escape sequence..
        /// </summary>
        internal static string GrammarParserErrors_InvalidEscape {
            get {
                return ResourceManager.GetString("GrammarParserErrors_InvalidEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must also be dynamic in length (&apos;+&apos;)..
        /// </summary>
        internal static string GrammarParserErrors_InvalidRepeatOptions {
            get {
                return ResourceManager.GetString("GrammarParserErrors_InvalidRepeatOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The grammar &apos;{0}&apos; has an invalid start point defined..
        /// </summary>
        internal static string GrammarParserErrors_InvalidStartDefined {
            get {
                return ResourceManager.GetString("GrammarParserErrors_InvalidStartDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The grammar &apos;{0}&apos; has no start point defined..
        /// </summary>
        internal static string GrammarParserErrors_NoStartDefined {
            get {
                return ResourceManager.GetString("GrammarParserErrors_NoStartDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule &apos;{0}&apos; is a template and requires expression arguments to reference properly..
        /// </summary>
        internal static string GrammarParserErrors_RuleIsTemplate {
            get {
                return ResourceManager.GetString("GrammarParserErrors_RuleIsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule &apos;{0}&apos; is never used..
        /// </summary>
        internal static string GrammarParserErrors_RuleNeverUsed {
            get {
                return ResourceManager.GetString("GrammarParserErrors_RuleNeverUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule &apos;{0}&apos; is not a template rule.  Parametered usage is not needed or allowed..
        /// </summary>
        internal static string GrammarParserErrors_RuleNotTemplate {
            get {
                return ResourceManager.GetString("GrammarParserErrors_RuleNotTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined token or rule reference &apos;{0}&apos;..
        /// </summary>
        internal static string GrammarParserErrors_UndefinedRuleReference {
            get {
                return ResourceManager.GetString("GrammarParserErrors_UndefinedRuleReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined reference &apos;{0}&apos;..
        /// </summary>
        internal static string GrammarParserErrors_UndefinedTokenReference {
            get {
                return ResourceManager.GetString("GrammarParserErrors_UndefinedTokenReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected: &apos;{0}&apos;..
        /// </summary>
        internal static string GrammarParserErrors_Unexpected {
            get {
                return ResourceManager.GetString("GrammarParserErrors_Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file..
        /// </summary>
        internal static string GrammarParserErrors_UnexpectedEndOfFile {
            get {
                return ResourceManager.GetString("GrammarParserErrors_UnexpectedEndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of line..
        /// </summary>
        internal static string GrammarParserErrors_UnexpectedEndOfLine {
            get {
                return ResourceManager.GetString("GrammarParserErrors_UnexpectedEndOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown symbol &apos;{0}&apos;..
        /// </summary>
        internal static string GrammarParserErrors_UnknownSymbol {
            get {
                return ResourceManager.GetString("GrammarParserErrors_UnknownSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string IndexerName {
            get {
                return ResourceManager.GetString("IndexerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Resources__.
        /// </summary>
        internal static string ResourcesAutoClassName {
            get {
                return ResourceManager.GetString("ResourcesAutoClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Resources__.
        /// </summary>
        internal static string ResourcesAutoClassName1 {
            get {
                return ResourceManager.GetString("ResourcesAutoClassName1", resourceCulture);
            }
        }
    }
}
