using System;
using System.Collections.Generic;
using System.Text;

namespace Oilexer.Types.Members
{
    public interface IAutoCommentMember :
        IMember
    {
        /// <summary>
        /// Returns/sets a string related to the auto-documentation summary comment generated by the system.
        /// </summary>
        string Summary { get; set; }
        /// <summary>
        /// Returns/sets a string related to the auto-documentation remarks comment generated by the system.
        /// </summary>
        string Remarks { get; set; }
    }
}
